# Generated by Django 4.0.3 on 2022-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
